#!/usr/bin/env python3
"""Emit docs/MCP_TOOLS.md from the two surfaces it maps between.

The document is a mapping, not a copy: for every tool the `d365fo-mcp` adapter
advertises, the `d365fo` commands that reach the same handler; and for every
command that has no MCP route, that fact stated rather than left to be noticed.

Both halves are read from the running code, never from a list kept by hand:

  d365fo schema --full --output json   the command manifest, including the
                                       `mcpTool` each command declares
  d365fo-mcp --legacy < tools/list     the tool list a client actually receives

A tool advertised but mapped from no command — or a command claiming a tool the
server does not advertise — is a drift the generator refuses to write around: it
exits non-zero and names both sides. That is the whole point of generating this
file. The upstream repo's MCP_TOOLS.md was a copy, and a copy cannot notice.

Usage:
  python scripts/emit-mcp-tools.py            write docs/MCP_TOOLS.md
  python scripts/emit-mcp-tools.py --check    fail if the file would change
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "MCP_TOOLS.md"

INIT = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
        "protocolVersion": "2024-11-05",
        "capabilities": {},
        "clientInfo": {"name": "emit-mcp-tools", "version": "1"},
    },
}
LIST = {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}


def run(cmd: list[str], stdin: str | None = None) -> str:
    """Run a build-output binary, or fall back to `dotnet run` from source."""
    proc = subprocess.run(
        cmd, input=stdin, capture_output=True, text=True, encoding="utf-8", cwd=ROOT
    )
    if proc.returncode != 0 and not proc.stdout.strip():
        sys.exit(f"{' '.join(cmd)} failed ({proc.returncode}):\n{proc.stderr[:2000]}")
    return proc.stdout


def cli_manifest() -> list[dict]:
    raw = run(cli_invocation("D365FO.Cli", "d365fo") + ["schema", "--full"])
    payload = json.loads(raw)
    return payload["data"]["commands"]


def mcp_tools() -> list[dict]:
    # --legacy is the built-in dispatcher: one JSON object per line, no SDK
    # framing, which is what makes it scriptable. The tool list it serves is the
    # same ToolCatalog the SDK transport serves.
    stdin = "\n".join(json.dumps(m) for m in (INIT, LIST)) + "\n"
    raw = run(cli_invocation("D365FO.Mcp", "d365fo-mcp") + ["--legacy"], stdin)
    for line in reversed([l for l in raw.splitlines() if l.strip()]):
        message = json.loads(line)
        if message.get("id") == 2:
            return message["result"]["tools"]
    sys.exit("The MCP adapter returned no tools/list response.")


def cli_invocation(project: str, exe: str) -> list[str]:
    """Prefer a built binary; fall back to `dotnet run` so a clean checkout works."""
    for configuration in ("Release", "Debug"):
        for name in (f"{exe}.exe", exe):
            candidate = ROOT / "src" / project / "bin" / configuration / "net10.0" / name
            if candidate.exists():
                return [str(candidate)]
    return ["dotnet", "run", "--project", f"src/{project}", "-c", "Release", "--"]


def render(commands: list[dict], tools: list[dict]) -> str:
    advertised = {t["name"]: t for t in tools}

    by_tool: dict[str, list[tuple[str, str]]] = defaultdict(list)
    unmapped: list[dict] = []
    for command in sorted(commands, key=lambda c: c["command"]):
        routes = command.get("mcpTool") or []
        if not routes:
            unmapped.append(command)
            continue
        for route in routes:
            name, _, discriminator = route.partition(" ")
            by_tool[name].append((command["command"], discriminator.strip("()")))

    claimed = set(by_tool)
    missing = sorted(claimed - set(advertised))
    orphan = sorted(set(advertised) - claimed)
    if missing or orphan:
        for name in missing:
            print(f"drift: commands map to '{name}', which the adapter does not advertise", file=sys.stderr)
        for name in orphan:
            print(f"drift: the adapter advertises '{name}', which no command maps to", file=sys.stderr)
        sys.exit(1)

    out: list[str] = []
    out.append("<!-- Generated by `python scripts/emit-mcp-tools.py`. Do not edit by hand. -->")
    out.append("# MCP tools ↔ CLI commands\n")
    out.append(
        "Every tool the bundled `d365fo-mcp` adapter advertises, and the `d365fo` "
        "commands that reach the same handler. Both columns are read from the running "
        "code — the command manifest (`d365fo schema --full`) and the adapter's own "
        "`tools/list` — so a tool that stops matching a command fails the generator "
        "rather than quietly outliving the mapping.\n"
    )
    out.append(
        f"**{len(advertised)} tools · {sum(len(v) for v in by_tool.values())} command routes · "
        f"{len(unmapped)} commands with no MCP route.**\n"
    )
    out.append(
        "The adapter is consolidated on purpose: one tool dispatches on a `type` / "
        "`objectType` / `mode` / `action` discriminator instead of shipping one tool per "
        "object kind. That keeps the schema payload a host injects every turn from growing "
        "with the object model — see [TOKEN_ECONOMICS.md](TOKEN_ECONOMICS.md) for what that "
        "payload actually measures.\n"
    )
    out.append("---\n")

    for name in sorted(advertised):
        tool = advertised[name]
        summary = (tool.get("description") or "").strip().split("\n")[0]
        if len(summary) > 240:
            summary = summary[:237].rstrip() + "…"
        out.append(f"### `{name}`\n")
        if summary:
            out.append(f"{summary}\n")
        out.append("| CLI command | Discriminator |")
        out.append("|---|---|")
        for command, discriminator in sorted(by_tool[name]):
            out.append(f"| `d365fo {command}` | {f'`{discriminator}`' if discriminator else '—'} |")
        out.append("")

    out.append("---\n")
    out.append("## Commands with no MCP tool\n")
    out.append(
        "Not an oversight, and not a gap in the adapter: these are operator and "
        "introspection commands, and an agent that already holds a connection has "
        "nothing to do with them. `CliMcpParityTests` carries the reason for each and "
        "fails the build if a new command joins this list without one.\n"
    )
    out.append("| Command | What it does |")
    out.append("|---|---|")
    for command in unmapped:
        description = (command.get("description") or "").strip().split("\n")[0]
        out.append(f"| `d365fo {command['command']}` | {description} |")
    out.append("")
    out.append("---\n")
    out.append("## See also\n")
    out.append("- [MCP_CONFIG.md](MCP_CONFIG.md) — pointing a client at the adapter.")
    out.append("- [MIGRATION_FROM_MCP.md](MIGRATION_FROM_MCP.md) — the old per-type tool names.")
    out.append("- [CAPABILITIES.md](CAPABILITIES.md) — what each command does, in full.")
    return "\n".join(out) + "\n"


def main() -> None:
    check = "--check" in sys.argv
    rendered = render(cli_manifest(), mcp_tools())

    if check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != rendered:
            sys.exit(
                f"{OUT.relative_to(ROOT)} is stale — run `python scripts/emit-mcp-tools.py` "
                "and commit the result."
            )
        print(f"{OUT.relative_to(ROOT)} is current.")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
